### ISSUE TITLE
deploy to test fails

### ISSUE THREAD

**Issue by vohmar** [internetee/registrant_center#77]
[1]   Running:  integration_spec.js                                                             (1 of 1)
[1]
[1]
[1]   1) An uncaught error was detected outside of a test
[1]
[1]   0 passing (491ms)
[1]   1 failing
[1]
[1]   1) An uncaught error was detected outside of a test:
[1]      CypressError: The following error originated from your test code, not from Cypress.
[1]
[1]   > `Cypress.Cookies.defaults` `whitelist` option has been renamed to `preserve`. Please rename `whitelist` to `preserve`.
[1]
[1] When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.
[1]
[1] Cypress could not associate this error to any specific test.
[1]
[1] We dynamically generated a new test to display this failure.
[1]       at warnOnWhitelistRenamed (https://localhost:4000/__cypress/runner/cypress_runner.js:150475:22)
[1]       at Object.defaults (https://localhost:4000/__cypress/runner/cypress_runner.js:150604:7)
[1]       at https://localhost:4000/__cypress/runner/cypress_runner.js:158389:16
[1]       at arrayEach (https://localhost:4000/__cypress/runner/cypress_runner.js:26586:11)
[1]       at Function.forEach (https://localhost:4000/__cypress/runner/cypress_runner.js:35466:14)
[1]       at evalScripts (https://localhost:4000/__cypress/runner/cypress_runner.js:158388:5)
[1]       at https://localhost:4000/__cypress/runner/cypress_runner.js:158396:113
[1]       at tryCatcher (https://localhost:4000/__cypress/runner/cypress_runner.js:10798:23)
[1]       at Promise._settlePromiseFromHandler (https://localhost:4000/__cypress/runner/cypress_runner.js:8733:31)
[1]       at Promise._settlePromise (https://localhost:4000/__cypress/runner/cypress_runner.js:8790:18)
[1]       at Promise._settlePromise0 (https://localhost:4000/__cypress/runner/cypress_runner.js:8835:10)
[1]       at Promise._settlePromises (https://localhost:4000/__cypress/runner/cypress_runner.js:8915:18)
[1]       at Promise._fulfill (https://localhost:4000/__cypress/runner/cypress_runner.js:8859:18)
[1]       at MappingPromiseArray.PromiseArray._resolve (https://localhost:4000/__cypress/runner/cypress_runner.js:9132:19)
[1]       at MappingPromiseArray._promiseFulfilled (https://localhost:4000/__cypress/runner/cypress_runner.js:7958:18)
[1]       at Promise._settlePromise (https://localhost:4000/__cypress/runner/cypress_runner.js:8795:26)

actions taken:
npm i
npx eslint --fix --ext jsx,js src server
npm run deploy

**Comment by vohmar** [comment]
different error this time: https://github.com/internetee/registrant_center/pull/78#issuecomment-853785946

**Comment by vohmar** [comment]
fixed
